### ISSUE TITLE
Potentially Misbehaving GPU

### ISSUE THREAD

**Issue by hickscorp** [openxla/xla#10660]
This issue might stem from this one - https://github.com/elixir-nx/xla/issues/80 - where the lower level setup isn't right.

It seems to me that something is misbehaving. As per  an advice I received, I thought I could see how Livebook behaves on the GPU. I configured  container spec for NVIDIA along with docker, and am running something like this:

```bash
docker run -p 8080:8080 -p 8081:8081 --pull always ghcr.io/livebook-dev/livebook:latest-cuda12.1
```

I'm trying to use "out of the box" Smart Cells that involve Nx / Bumblebee / XLA.
But as soon as I try to run one, the GPU goes  OOM and it seems to me that it could take much more than that (It has around 6GB of memory).
I've tried various options (Eg model `backend: {EXLA.Backend, client: :host}` along with different combinations of `defn_options: [compiler: EXLA, lazy_transfers: :always]` but still it just seems to postpone the crash (When the inference runs vs when the model loads).

Error looks like this:

```
** (RuntimeError) Out of memory while trying to allocate 117964800 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  112.50MiB
              constant allocation:         0B
        maybe_live_out allocation:  112.50MiB
     preallocated temp allocation:         0B
                 total allocation:  225.00MiB
              total fragmentation:         0B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 112.50MiB
		Entry Parameter Subshape: f32[29491200]
		==========================

	Buffer 2:
		Size: 112.50MiB
		XLA Label: copy
		Shape: f32[1280,2560,3,3]
		==========================

	Buffer 3:
		Size: 8B
		XLA Label: tuple
		Shape: (f32[1280,2560,3,3])
		==========================


    (exla 0.6.4) lib/exla/executable.ex:56: EXLA.Executable.unwrap!/1
    (exla 0.6.4) lib/exla/executable.ex:19: EXLA.Executable.run/3
    (exla 0.6.4) lib/exla/defn.ex:346: EXLA.Defn.maybe_outfeed/7
    (stdlib 5.1.1) timer.erl:270: :timer.tc/2
    (exla 0.6.4) lib/exla/defn.ex:283: anonymous fn/7 in EXLA.Defn.__compile__/4
    (nx 0.6.4) lib/nx/defn.ex:443: Nx.Defn.do_jit_apply/3
    (bumblebee 0.4.2) lib/bumblebee/conversion/pytorch/loader.ex:79: Bumblebee.Conversion.PyTorch.Loader.object_resolver/1
    #cell:hacnfhjbfkcplhp3:6: (file)
```

The GPU in this laptop is as follows (definetely not a desktop GPU, but still high end for a laptop):

```
Mon Mar 18 18:42:40 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8              4W /   55W |    5412MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    589608      C   ...lib/erlang/erts-14.1.1/bin/beam.smp       5406MiB |
+-----------------------------------------------------------------------------------------+
```

Is there any way for me to reliably know if my setup is right? For example a livebook having parameters **known to work** within spec of this GPU?

**Comment by cheshire** [comment]
The GPU has 6GBs, but OOM happens at few hundred MBs. Something is off, maybe reboot? Here your screenshot also shows 5GB taken by something else.

**Comment by hickscorp** [comment]
As soon as XLA allocates, it goes to 5gb upfront.
I'll reboot and try again. I thought something was off yes. Thanks!

**Comment by hickscorp** [comment]
@cheshire confirmed - after a reboot same symptoms. As soon as I start a playbook with XLA related code, the GPU reserves 5406MB of memory.

I'm aware that this might very well not be XLA related... But given the knowledge I've seen around here, I'd still like to ask :)

```
20:42:13.770 [info] Stats: 
Limit:                      5566405017
InUse:                      5486330368
MaxInUse:                   5486330368
NumAllocs:                         991
MaxAllocSize:                151781376
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0
```

**Comment by hickscorp** [comment]
Well actually - it seems to be behaving slightly differently now...
I'm getting:

```
10:42:32.799 [error] Process #PID<0.3493.0> on node :"dl53oscu-livebook_server@41cae5e4832c" raised an exception
** (Axon.CompileError) exception found when compiling layer Axon.Layers.embedding/3 named decoder_embedder.position_embedding:

    ** (ArgumentError) indices must be an integer tensor, got {:f, 32}
        (nx 0.6.4) lib/nx.ex:14150: Nx.take/3
    

(pass debug: true to build/compile see where the layer was defined)


Compiling of the model was initiated at:

    (bumblebee 0.4.2) lib/bumblebee/text/generation.ex:488: Bumblebee.Text.Generation."__defn:greedy_step__"/10
    (bumblebee 0.4.2) lib/bumblebee/text/generation.ex:434: anonymous fn/9 in Bumblebee.Text.Generation."__defn:greedy__"/7
    (nx 0.6.4) lib/nx/defn/expr.ex:517: Nx.Defn.Expr.while_vectorized/7
    (bumblebee 0.4.2) lib/bumblebee/text/generation.ex:431: Bumblebee.Text.Generation."__defn:greedy__"/7
    (nx 0.6.4) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (exla 0.6.4) lib/exla/defn.ex:387: anonymous fn/4 in EXLA.Defn.compile/8
```

Trying a text  summary with BART.

**Comment by cheshire** [comment]
> As soon as XLA allocates, it goes to 5gb upfront.

Yes, it's expected, the BFC allocator gets all the memory. But then it's failing to allocate a few hundred MBs, so something is interfering. Try to run with `TF_CPP_VMODULE=bfc_allocator=5 TF_CPP_MIN_LOG_LEVEL=0` to see what's going on. Maybe you're trying to run two XLA processes, and the previous one gets all the memory?

**Comment by hickscorp** [comment]
Ok so I'm trying now.

`TF_CPP_VMODULE=bfc_allocator=5 TF_CPP_MIN_LOG_LEVEL=0 iex -S mix phx.server` will do?
No, no duplicate XLA processes... Well I don't know. Unless VSCode plugins / code servers start my application but I doubt it.

**Comment by penumallas1261** [comment]
Hi @hickscorp ,

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ?

**Comment by hickscorp** [comment]
Can't really confirm or not... I dropped from using XLA all together.
I'm closing the issue, but if someone experiences the same thing, feel free to re-open!
