### ISSUE TITLE
JAX manual sharding triggers assertions in SPMD partitioner

### ISSUE THREAD

**Issue by joker-eph** [openxla/xla#4340]
```
2023-07-18 23:43:01.804619: F external/xla/xla/hlo/ir/hlo_sharding.cc:961] Check failed: !IsManual() 

Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350238208) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350238208) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350238208) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350238208, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c8b476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c717f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fff9418a493 in tsl::internal::LogMessageFatal::~LogMessageFatal (this=0x7fffffff2df0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at external/tsl/tsl/platform/default/logging.cc:376
#6  0x00007fff9212d051 in xla::HloSharding::NumTiles (this=0x555556a48670) at external/xla/xla/hlo/ir/hlo_sharding.cc:961
#7  0x00007fff8a1c0bd0 in xla::spmd::PartitionedHlo::Reshard (this=0x555556bf7318, target=..., pad_value=std::optional<xla::Literal> [no contained value]) at external/xla/xla/service/spmd/spmd_partitioner.cc:403
#8  0x00007fff8a1dc03f in xla::spmd::SpmdPartitioningVisitor::HandleElementwise (this=0x555556eb0ae0, hlo=0x555556bfb200) at external/xla/xla/service/spmd/spmd_partitioner.cc:2615
#9  0x00007fff8a1d9428 in xla::spmd::SpmdPartitioningVisitor::DefaultAction (this=0x555556eb0ae0, hlo=0x555556bfb200) at external/xla/xla/service/spmd/spmd_partitioner.cc:2363
#10 0x00007fff87add2cf in xla::DfsHloVisitorWithDefaultBase<xla::HloInstruction*>::HandleElementwiseUnary (this=0x555556eb0ae0, hlo=0x555556bfb200) at external/xla/xla/hlo/ir/dfs_hlo_visitor_with_default.h:53
#11 0x00007fff9201264b in xla::DfsHloVisitorBase<xla::HloInstruction*>::HandleCopy (this=0x555556eb0ae0, hlo=0x555556bfb200) at external/xla/xla/hlo/ir/dfs_hlo_visitor.h:94
#12 0x00007fff92084810 in xla::HloInstruction::Visit<xla::HloInstruction*> (this=0x555556bfb200, visitor=0x555556eb0ae0) at external/xla/xla/hlo/ir/hlo_instruction.cc:3746
#13 0x00007fff9207970f in xla::PostOrderDFS<xla::DfsHloVisitorBase<xla::HloInstruction*> >(xla::HloInstruction *, xla::DfsHloVisitorBase<xla::HloInstruction*> *, std::optional<absl::lts_20230125::FunctionRef<bool(std::pair<int, const xla::HloInstruction*>, std::pair<int, const xla::HloInstruction*>)> >, bool)
    (root=0x555556c68b10, visitor=0x555556eb0ae0, operand_order=std::optional<absl::lts_20230125::FunctionRef<bool(std::pair<int, const xla::HloInstruction*>, std::pair<int, const xla::HloInstruction*>)>> [no contained value], ignore_control_predecessors=false)
    at external/xla/xla/hlo/ir/hlo_instruction.cc:3997
#14 0x00007fff92086c52 in xla::HloInstruction::Accept<xla::HloInstruction*> (this=0x555556c68b10, visitor=0x555556eb0ae0, call_finish_visit=false, ignore_control_predecessors=false) at external/xla/xla/hlo/ir/hlo_instruction.cc:4044
#15 0x00007fff86f393cc in xla::HloComputation::Accept<xla::HloInstruction*> (this=0x555556dde960, visitor=0x555556eb0ae0) at external/xla/xla/hlo/ir/hlo_computation.h:846
#16 0x00007fff8a1f4f0a in xla::spmd::SpmdPartitioningVisitor::DoPartition (this=0x555556eb0ae0, computation=0x555556dde960, root_sharding=..., options=...) at external/xla/xla/service/spmd/spmd_partitioner.cc:4701
#17 0x00007fff8a1f77f9 in xla::spmd::SpmdPartitioner::PartitionComputation (this=0x555556e5a300, computation=0x555556dde960, root_sharding=..., next_channel_id=0x7fffffff4d38, logger=0x7fffffff4dc0, call_graph=...) at external/xla/xla/service/spmd/spmd_partitioner.cc:4981

```

I added a unit-test here: https://github.com/joker-eph/xla/commit/e19e88c0ddcf354fb2512bf6a192726c07e1faef

**Comment by joker-eph** [comment]
Log:
```
2023-07-19 00:24:25.457796: I external/xla/xla/service/spmd/spmd_partitioner.cc:4698] Partitioning computation main.38 for 1 replicas and 8 partitions
2023-07-19 00:24:25.457808: I external/xla/xla/hlo/ir/hlo_computation.cc:1155] Unreachable roots:%get-tuple-element.19 = f32[32]{0} get-tuple-element((f32[32,128]{1,0}, f32[32]{0}) %custom-call.17), index=1, sharding={replicated}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/vmap(vmap(xmap(<unnamed function>)))/fake_custom_call_fwd[mesh=None epsilon=1e-05]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=103}
2023-07-19 00:24:25.457816: I external/xla/xla/hlo/ir/hlo_computation.h:844] Traversing unreachable root: %get-tuple-element.19 = f32[32]{0} get-tuple-element((f32[32,128]{1,0}, f32[32]{0}) %custom-call.17), index=1, sharding={replicated}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/vmap(vmap(xmap(<unnamed function>)))/fake_custom_call_fwd[mesh=None epsilon=1e-05]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=103}
2023-07-19 00:24:25.457821: I external/xla/xla/hlo/ir/hlo_instruction.cc:4043] HloInstruction::Accept(%get-tuple-element.19)
2023-07-19 00:24:25.457838: I external/xla/xla/hlo/ir/hlo_instruction.cc:3996] Visiting HLO %Arg_0.1
2023-07-19 00:24:25.457848: I external/xla/xla/shape_util.cc:937] Validating shape size: f32[1,32,128]
2023-07-19 00:24:25.457851: I external/xla/xla/shape_util.cc:966] Shape size is valid: 16384
2023-07-19 00:24:25.457876: I external/xla/xla/hlo/ir/hlo_instruction.cc:3996] Visiting HLO %copy.5
2023-07-19 00:24:25.457893: I external/xla/xla/service/spmd/spmd_partitioner.cc:433] Resharding %param = f32[1,32,128]{2,1,0} parameter(0), sharding={devices=[2,1,1,4]0,1,2,3,4,5,6,7 last_tile_dim_replicate} from {devices=[2,1,1,4]0,1,2,3,4,5,6,7 last_tile_dim_replicate} to {replicated}
2023-07-19 00:24:25.457924: I external/xla/xla/shape_util.cc:937] Validating shape size: f32[2,32,128]
2023-07-19 00:24:25.457928: I external/xla/xla/shape_util.cc:966] Shape size is valid: 32768
2023-07-19 00:24:25.457981: I external/xla/xla/hlo/ir/hlo_instruction.cc:2062] CloneWithNewOperands:
  %copy.5 = f32[2,32,128]{2,1,0} copy(f32[2,32,128]{2,1,0} %Arg_0.1), sharding={replicated}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/full_to_shard[axes=OrderedDict() mesh=Mesh(device_ids=array([[0, 1, 2, 3],\n       [4, 5, 6, 7]]), axis_names=(\'pp\', \'tp\')) manual_axes=(\'pp\', \'tp\')]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=145}
2023-07-19 00:24:25.457989: I external/xla/xla/hlo/ir/hlo_instruction.cc:2063]   new operands:
2023-07-19 00:24:25.457993: I external/xla/xla/hlo/ir/hlo_instruction.cc:2065]     %all-gather
2023-07-19 00:24:25.457999: I external/xla/xla/shape_util.cc:937] Validating shape size: f32[2,32,128]
2023-07-19 00:24:25.458003: I external/xla/xla/shape_util.cc:966] Shape size is valid: 32768
2023-07-19 00:24:25.458054: I external/xla/xla/hlo/ir/hlo_instruction.cc:3996] Visiting HLO %custom-call.8
2023-07-19 00:24:25.458067: I external/xla/xla/shape_util.cc:937] Validating shape size: f32[2,32,128]
2023-07-19 00:24:25.458072: I external/xla/xla/shape_util.cc:966] Shape size is valid: 32768
2023-07-19 00:24:25.458107: I external/xla/xla/hlo/ir/hlo_instruction.cc:3996] Visiting HLO %copy.4
User: %copy.4 = f32[2,32,128]{2,1,0} copy(f32[2,32,128]{2,1,0} %custom-call.8), sharding={devices=[2,1,1,4]0,1,2,3,4,5,6,7 last_tile_dim_replicate}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/vmap(vmap(xmap(<unnamed function>)))/full_to_shard[axes=OrderedDict([(\'pp\', 0)]) mesh=Mesh(device_ids=array([[0, 1, 2, 3],\n       [4, 5, 6, 7]]), axis_names=(\'pp\', \'tp\')) manual_axes=(\'pp\',)]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=103}
 Operand: %custom-call.8 = f32[2,32,128]{2,1,0} custom-call(f32[2,32,128]{2,1,0} %copy.5), custom_call_target="SPMDFullToShardShape", sharding={manual}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/full_to_shard[axes=OrderedDict() mesh=Mesh(device_ids=array([[0, 1, 2, 3],\n       [4, 5, 6, 7]]), axis_names=(\'pp\', \'tp\')) manual_axes=(\'pp\', \'tp\')]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=145}, backend_config="unspecified_dims=[0,1,2]"
```

The HLO before the crash looks like:

```
ENTRY %main.38 (Arg_0.1: f32[2,32,128], Arg_1.2: f32[2,128], Arg_2.3: f32[128]) -> f32[] {
  %Arg_0.1 = f32[2,32,128]{2,1,0} parameter(0), sharding={devices=[2,1,1,4]0,1,2,3,4,5,6,7 last_tile_dim_replicate}
  %copy.5 = f32[2,32,128]{2,1,0} copy(f32[2,32,128]{2,1,0} %Arg_0.1), sharding={replicated}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/full_to_shard[axes=OrderedDict() mesh=Mesh(device_ids=array([[0, 1, 2, 3],\n       [4, 5, 6, 7]]), axis_names=(\'pp\', \'tp\')) manual_axes=(\'pp\', \'tp\')]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=145}
  %custom-call.8 = f32[2,32,128]{2,1,0} custom-call(f32[2,32,128]{2,1,0} %copy.5), custom_call_target="SPMDFullToShardShape", sharding={manual}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/full_to_shard[axes=OrderedDict() mesh=Mesh(device_ids=array([[0, 1, 2, 3],\n       [4, 5, 6, 7]]), axis_names=(\'pp\', \'tp\')) manual_axes=(\'pp\', \'tp\')]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=145}, backend_config="unspecified_dims=[0,1,2]"
  %copy.4 = f32[2,32,128]{2,1,0} copy(f32[2,32,128]{2,1,0} %custom-call.8), sharding={devices=[2,1,1,4]0,1,2,3,4,5,6,7 last_tile_dim_replicate}, metadata={op_name="pjit(<unnamed wrapped function>)/jit(main)/vmap(xmap(<lambda>))/vmap(vmap(xmap(<unnamed function>)))/full_to_shard[axes=OrderedDict([(\'pp\', 0)]) mesh=Mesh(device_ids=array([[0, 1, 2, 3],\n       [4, 5, 6, 7]]), axis_names=(\'pp\', \'tp\')) manual_axes=(\'pp\',)]" source_file="delay_xmap_lowering_tiny_repro.py" source_line=103}
```
