### ISSUE TITLE
[Bug][TPU] channel is used for multiple host send/recv instructions

### ISSUE THREAD

**Issue by neel04** [openxla/xla#7904]
This is very recent bug (appeared in the last few days or so). I have tested it:
1. On Kaggle TPUs
2. On Docker on a GCP TPU VM
3. On Conda on TPU VM

On TPUv2, TPUv3, and TPUv4.

```py
Traceback (most recent call last):
  File "/kaggle/working/ReAct_Jax/train_model.py", line 47, in <module>
    main(key)
  File "/kaggle/working/ReAct_Jax/train_model.py", line 43, in main
    trainer.train(args.epochs, trainloader, valloader, key)
  File "/kaggle/working/ReAct_Jax/ReAct/utils/trainer.py", line 235, in train
    loss, model, opt_state = make_step(model, seq, label, pad_mask, rndm_n, rndm_k,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/equinox/_jit.py", line 206, in __call__
    return self._call(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/equinox/_module.py", line 875, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/equinox/_jit.py", line 198, in _call
    out = self._cached(dynamic_donate, dynamic_nodonate, static)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: during context [pre-optimization]: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/hlo_verifier.cc:2330) instructions.size() == 2 channel 11 is used for multiple host send/recv instructions
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

- This is occurring (I think) on the JIT compilation part of the main training step of my NN. I'm using `equinox`, with jax's autoparallelization features that utilizes sharding and `device_put` method.

- This script was working fine a few week ago, and for several runs for the past 2 months. As mentioned, it works perfectly on GPU too.

- Apart from that, I'm not sure how else I can debug this. I was trying to find a minimum reproducible example but I can't find anything else.

- The only change in my setup has been my own code - which I've verified breaks with the exam same error on earlier versions, so its an issue i suspect with `libtpu` or `xla`.

This is the script I use to setup the environment on Kaggle's TPU. This uses `python3.11` and gets `jax[tpu]` exactly as recommended in the docs.

It has some redundant commands, but it had been working fine for me for the past few months, so I'm attaching the entirety of the setup cell to ensure nothing is missed, and you can reproduce the exact environment in full.

```py
!apt update
!wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tar.xz
!tar -xf Python-3.11.0.tar.xz
!cd Python-3.11.0; ./configure --enable-optimizations; make -j$(nproc); make altinstall
!python3.11 --version

!python3.11 -m pip install -U -q jax[tpu] optax equinox jax jaxlib wandb einops torch tqdm jaxtyping
!python3.11 -m pip install -q jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
!python3.11 -m pip install -U -q jax jax[tpu] optax equinox jaxlib wandb einops torch tqdm jaxtyping
!python3.11 -m pip install -q equinox optax jax jaxlib wandb einops torch tqdm jaxtyping datasets icecream tokenizers
!pip3 uninstall tensorflow -y
```

### Full stacktrace

<details>

<summary>Full traceback:</summary>

```py

E1219 15:04:07.952504809   17552 oauth2_credentials.cc:238]            oauth_fetch: UNKNOWN:C-ares status is not ARES_SUCCESS qtype=A name=metadata.google.internal. is_balancer=0: Domain name not found {grpc_status:2, created_time:"2023-12-19T15:04:07.952484742+00:00"}
/usr/local/lib/python3.11/site-packages/datasets/load.py:2096: FutureWarning: 'ignore_verifications' was deprecated in favor of 'verification_mode' in version 2.9.1 and will be removed in 3.0.0.
You can remove this warning by passing 'verification_mode=no_checks' instead.
  warnings.warn(
Downloading readme: 100%|██████████| 1.02k/1.02k [00:00<00:00, 9.28MB/s]
/usr/local/lib/python3.11/site-packages/huggingface_hub/repocard.py:105: UserWarning: Repo card metadata block was not found. Setting CardData to empty.
  warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")

https://symbolize.stripped_domain/r/?trace=5898b7696139,7d446be50fcf&map= 
*** SIGTERM received by PID 18306 (TID 18306) on cpu 52 from PID 17412; stack trace: ***
PC: @     0x5898b7696139  (unknown)  PyObject_CallOneArg
    @     0x7d425b26ab27        928  (unknown)
    @     0x7d446be50fd0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=5898b7696139,7d425b26ab26,7d446be50fcf&map= 
E1219 15:04:31.099973   18306 coredump_hook.cc:388] RAW: Remote crash gathering disabled for SIGTERM.
E1219 15:04:31.112627   18306 process_state.cc:807] RAW: Raising signal 15 with default behavior
Setting num_proc from 96 to 4 for the train split as it only contains 4 shards.
Generating train split: 2119719 examples [00:02, 768571.76 examples/s] 
https://symbolize.stripped_domain/r/?trace=5898b76b82d6,7d446be50fcf&map= 
*** SIGTERM received by PID 18310 (TID 18310) on cpu 35 from PID 17412; stack trace: ***
PC: @     0x5898b76b82d6  (unknown)  _PyDict_LoadGlobal
    @     0x7d425b26ab27        928  (unknown)
    @     0x7d446be50fd0  162515728  (unknown)
    @     0x5898b78e9ce0  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=5898b76b82d6,7d425b26ab26,7d446be50fcf,5898b78e9cdf&map= 
E1219 15:04:33.945893   18310 coredump_hook.cc:388] RAW: Remote crash gathering disabled for SIGTERM.
E1219 15:04:33.980399   18310 process_state.cc:807] RAW: Raising signal 15 with default behavior
Setting num_proc from 96 back to 1 for the validation split to disable multiprocessing as it only contains one shard.
Generating validation split: 21990 examples [00:00, 218217.65 examples/s]
/usr/local/lib/python3.11/site-packages/datasets/load.py:2096: FutureWarning: 'ignore_verifications' was deprecated in favor of 'verification_mode' in version 2.9.1 and will be removed in 3.0.0.
You can remove this warning by passing 'verification_mode=no_checks' instead.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/huggingface_hub/repocard.py:105: UserWarning: Repo card metadata block was not found. Setting CardData to empty.
  warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")

Number of devices: 8

Model # of parameters: 1.72M
# of recurrent parameters: 0.91M

Model: React(
  max_iters=5,
  bottleneck=96,
  SEQLEN=192,
  pos_enc=bf16[192,96],
  embed_layer=Embedding(
    num_embeddings=4096,
    embedding_size=96,
    weight=bf16[4096,96]
  ),
  main_block=RecurrentModule(
    attention_blocks=[
      AttentionBlock(
        seqlen=192,
        n_heads=2,
        bottleneck=192,
        attn_gate=MultiheadAttention(
          query_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          key_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          value_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          output_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          dropout=Dropout(p=0.02, inference=False),
          num_heads=2,
          query_size=192,
          key_size=192,
          value_size=192,
          output_size=192,
          qk_size=96,
          vo_size=96,
          use_query_bias=True,
          use_key_bias=True,
          use_value_bias=True,
          use_output_bias=True
        ),
        ln1=LayerNorm(
          shape=(192,),
          eps=1e-05,
          use_weight=True,
          use_bias=True,
          weight=bf16[192],
          bias=bf16[192]
        ),
        ln2=LayerNorm(
          shape=(192,),
          eps=1e-05,
          use_weight=True,
          use_bias=True,
          weight=bf16[192],
          bias=bf16[192]
        ),
        mlp=MLP(
          layers=[
            LinearProj(
              bias=bf16[768],
              weight=bf16[192,768],
              input_dim=192,
              output_dim=768,
              use_bias=True
            ),
            Lambda(fn=NewGELU()),
            LinearProj(
              bias=bf16[192],
              weight=bf16[768,192],
              input_dim=768,
              output_dim=192,
              use_bias=True
            )
          ],
          dropout=Dropout(p=0.02, inference=False)
        )
      ),
      AttentionBlock(
        seqlen=192,
        n_heads=2,
        bottleneck=192,
        attn_gate=MultiheadAttention(
          query_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          key_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          value_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          output_proj=Linear(
            weight=bf16[192,192],
            bias=bf16[192],
            in_features=192,
            out_features=192,
            use_bias=True
          ),
          dropout=Dropout(p=0.02, inference=False),
          num_heads=2,
          query_size=192,
          key_size=192,
          value_size=192,
          output_size=192,
          qk_size=96,
          vo_size=96,
          use_query_bias=True,
          use_key_bias=True,
          use_value_bias=True,
          use_output_bias=True
        ),
        ln1=LayerNorm(
          shape=(192,),
          eps=1e-05,
          use_weight=True,
          use_bias=True,
          weight=bf16[192],
          bias=bf16[192]
        ),
        ln2=LayerNorm(
          shape=(192,),
          eps=1e-05,
          use_weight=True,
          use_bias=True,
          weight=bf16[192],
          bias=bf16[192]
        ),
        mlp=MLP(
          layers=[
            LinearProj(
              bias=bf16[768],
              weight=bf16[192,768],
              input_dim=192,
              output_dim=768,
              use_bias=True
            ),
            Lambda(fn=NewGELU()),
            LinearProj(
              bias=bf16[192],
              weight=bf16[768,192],
              input_dim=768,
              output_dim=192,
              use_bias=True
            )
          ],
          dropout=Dropout(p=0.02, inference=False)
        )
      )
    ],
    reshape_layer=LinearProj(
      bias=bf16[96],
      weight=bf16[192,96],
      input_dim=192,
      output_dim=96,
      use_bias=True
    )
  ),
  post_ln=LayerNorm(
    shape=(96,),
    eps=1e-05,
    use_weight=True,
    use_bias=True,
    weight=bf16[96],
    bias=bf16[96]
  ),
  out_head=output_head(
    out_proj=LinearProj(
      bias=bf16[4096],
      weight=bf16[96,4096],
      input_dim=96,
      output_dim=4096,
      use_bias=True
    )
  )
)
0it [00:06, ?it/s]
Traceback (most recent call last):
  File "/kaggle/working/ReAct_Jax/train_model.py", line 47, in <module>
    main(key)
  File "/kaggle/working/ReAct_Jax/train_model.py", line 43, in main
    trainer.train(args.epochs, trainloader, valloader, key)
  File "/kaggle/working/ReAct_Jax/ReAct/utils/trainer.py", line 235, in train
    loss, model, opt_state = make_step(model, seq, label, pad_mask, rndm_n, rndm_k,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/equinox/_jit.py", line 206, in __call__
    return self._call(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/equinox/_module.py", line 875, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/equinox/_jit.py", line 198, in _call
    out = self._cached(dynamic_donate, dynamic_nodonate, static)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: during context [pre-optimization]: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/hlo_verifier.cc:2330) instructions.size() == 2 channel 11 is used for multiple host send/recv instructions
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

</details>

**Comment by neel04** [comment]
```py
def n_k_loop(model: eqx.Module, input_arr: Array, pad_mask: Array, n: int, k: int, key: PRNGKeyArray) -> Array:
    key1, key2 = jax.random.split(key, 2)

    output, _ = model(input_arr, k, pad_mask=pad_mask, prev_thought=None, key=key2)

    return output

def k_loop(model: eqx.Module, input_arr: Array, pad_mask: Array, n: int, k: int, key: PRNGKeyArray) -> Array:
    key1, key2 = jax.random.split(key, 2)

    output, _ = model(input_arr, n, pad_mask=pad_mask, prev_thought=None, key=key1)

    return output

@partial(jax.jit, static_argnums=(5,))
def router(model: eqx.Module, input_arr: Array, pad_mask: Array, n: int, k: int, key: PRNGKeyArray) -> Array:
    idx = jax.random.randint(key, (), 0, 2)

    out1 = n_k_loop(model, input_arr, pad_mask, n, k, key)
    out2 = k_loop(model, input_arr, pad_mask, n, k, key)

    return out1 * idx + out2 * (1 - idx)
```

So, as far as I triangulated, having the output for `router` (which represents the model's forward pass and yields the logits for computing loss) being depended on the execution of **both** `n_k_loop` and `k_loop` causes the problem.

If I remove one of the terms `out1` or `out2` in their linear combination in the last `return` statement, then it works. 

Why would calling `model` twice trigger this bug? 🤔

**Comment by BitPhinix** [comment]
Experiencing this as well when using `diffrax.VirtualBrownianTree` on TPUs

**Comment by neel04** [comment]
> Experiencing this as well when using `diffrax.VirtualBrownianTree` on TPUs

Check out https://github.com/patrick-kidger/equinox/issues/628#issuecomment-1872524191 which resolves the issue - the problem here is related to how `equinox` handles host callbacks.

You can disable callbacks with the flag - make sure to pass that flag using the `-e` if you're using docker!

**Comment by penumallas1261** [comment]
Hi @neel04 ,

Closing the issue because we believe the question has been answered, Please feel free to reopen the issue if you still have a concern. Thanks!
